update: init vm store, utility functions to help set store up.

diff --git a/qemu-helpers/bin/qemu-go b/qemu-helpers/bin/qemu-go
--- a/qemu-helpers/bin/qemu-go
+++ b/qemu-helpers/bin/qemu-go
@@ -18,15 +18,24 @@ OPTIONS:
    -b      Use the base directory where qemu files/disks are stored.
    -m      Macaddress to use for qemu VM.
    -i      Network interface to use.
+   -c      First time init for vm store
 EOF
 }
+
+if [ -z $HLUSER ] ; then
+    HLUSER=$USER
+fi
+if [ -z $HLGROUP ] ; then
+    HLGROUP=$GROUP
+fi
 
 MACADDR="52:54:00:12:34:11"
 INTERFACE="tap0"
 ARCH=""
 ACTION=""
 BASEDIR=""
-while getopts “hdva:r:b:m:i:” OPTION
+INITVMDIR=""
+while getopts “hdva:r:b:m:i:c” OPTION
 do
     case $OPTION in
         h)
@@ -55,6 +64,9 @@ do
         i)
             INTERFACE=$OPTARG
             ;;
+        c)
+            INITVMDIR="yes"
+            ;;
         ?)
             usage
             exit
@@ -62,18 +74,50 @@ do
     esac
 done
 
+chown_dir_to_target_install_user_group ()
+{
+
+    if [ ! -z $1 ] ; then
+        TARGETDIR=$1
+        sudo chown -Rv $HLUSER:$HLGROUP $TARGETDIR || fail "Expected chown to succeed"
+    fi
+    return 0
+}
+
+list_vms_dir ()
+{
+    verbose "Checking $HLDESTDISKDIR"
+    ls -1 $HLDESTDISKDIR
+}
+
+init_vms_dir ()
+{
+    sudo mkdir -v $HLBASEINSTALL || fail "Couldn't create $HLBASEINSTALL"
+    chown_dir_to_target_install_user_group $HLBASEINSTALL || fail "Couldn't set user:group ($HLUSER:$HLGROUP) on $HLBASEINSTALL"
+    sudo mkdir -v $HLDESTDISKDIR -p || fail "Couldn't create $HLDESTDISKDIR"
+    chown_dir_to_target_install_user_group $HLDESTDISKDIR || fail "Couldn't set user::group ($HLUSER:$HLGROUP) on $HLDESTDISKDIR"
+    return 0
+}
+
 debug "Sourcing helper paths"
 
 source qemu-helper-paths
 
-echo $ACTION
+if [ ! -z $INITVMDIR ] ; then
+    init_vms_dir || fail "Failed to initialize"
+fi
+
+if [ -z $ARCH ] ; then
+    list_vms_dir
+    exit 0
+fi
 
 if [ -z $ARCH ] ; then usage ; fail "no ARCH specified" ; fi
 if [ -z $ACTION ] ; then usage ; fail "no ACTION specified i.e., $0 ARCH [install|run]" ; fi
 
-if [ -z $BASEDIR ] ; then info "Using CWD for qemu disk store"; fi
+if [ -z $BASEDIR ] ; then info "Using $HLDESTDISKDIR for qemu disk store" && cd $HLDESTDISKDIR ; fi
 if [ ! -z $BASEDIR ] ; then cd $BASEDIR || fail "Couldn't change directory to qemu disk store at: \"$BASEDIR\""; fi
-if [ ! -d $ARCH ] ; then usage ; fail "Expected architecture directory \"$ARCH\" to exist" ; fi
+if [ ! -d $ARCH ] ; then usage ; fail "Expected architecture directory \"$ARCH\" to exist in `pwd`" ; fi
 cd $ARCH
 
 QEMUBIN=`which qemu-system-$ARCH`
@@ -91,7 +135,7 @@ if [[ $ACTION == "install" ]] ; then
     read -p"go?"
     qemu-system-$ARCH -hda $HARDDISK -kernel $KERNEL -initrd $INITRD -append "root=/dev/ram console=ttyS0" -nographic
 elif [[ $ACTION == "run" ]] ; then
-    qemu-system-$ARCH \
+    sudo qemu-system-$ARCH \
             -hda $HARDDISK \
             -kernel $KERNEL \
             -append "root=/dev/sda1 console=ttyS0" \
